#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.ae88807e44f106f7dbacb3b459d6569b48eb2b01.name = "Upgrade from 19.0.3"
#    test_upgrade_from.7fe322da61737fe7060a4ccd638760ae06538484.name = "Upgrade from 21.0.4"
#    test_upgrade_from.90d17ffa43765a9f66786534adc46881f79e6f72.name = "Upgrade from 22.0.4"
