#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE conf file
#=================================================

ynh_replace --file="$install_dir/htdocs/conf/conf.php" \
    --match="$old_domain$old_path" \
    --replace="$new_domain$new_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
