#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

ynh_app_config_apply() {
    _ynh_app_config_apply
    
    if [ "${changed[syncyunohost_install]}" == "true" ] && [ $syncyunohost_install == "false" ]
    then
        ynh_print_info "syncyunohost install"
        syncyunohost_module_install
        ynh_app_setting_set --key=syncyunohost --value=1
    elif [ "${changed[syncyunohost_uninstall]}" == "true" ] && [ $syncyunohost_uninstall == "false" ]
    then
        ynh_print_info "syncyunohost uninstall"
        syncyunohost_module_remove
        ynh_app_setting_set --key=syncyunohost --value=0
    fi
    if [ "${changed[syncyunohost_enabled]}" == "true" ] && [ $syncyunohost_enabled == "true" ]
    then
        syncyunohost_modules_activate
    elif [ "${changed[syncyunohost_enabled]}" == "true" ] && [ $syncyunohost_enabled == "false" ]
    then
        syncyunohost_modules_deactivate
    fi
}

ynh_app_config_run $1
