#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

# Apply Yunohost app's config
ynh_app_config_apply() {
    _ynh_app_config_apply

    if [[ "${changed[syncyunohost_base_domain]}" == "true" || "${changed[syncyunohost_main_group]}" == "true"  || "${changed[syncyunohost_enabled]}" == "true" ]] && [ $syncyunohost_enabled == "true" ]
    then
        syncyunohost_modules_activate
    elif [ "${changed[syncyunohost_enabled]}" == "true" ] && [ $syncyunohost_enabled == "false" ]
    then
        syncyunohost_modules_deactivate
    fi
}

ynh_app_config_run $1
