#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated nginx config
ynh_config_remove_nginx

# Remove the dedicated php-fpm config
ynh_config_remove_phpfpm

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# remove syncyunohost module
if [ "$syncyunohost_enabled" == "true" ], then
syncyunohost_scripts_remove
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
