#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


app=$YNH_APP_INSTANCE_NAME


# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# Remove sources
sudo rm -rf /var/www/$app

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# PHP
sudo rm -f /etc/php5/fpm/pool.d/$app.conf
sudo service php5-fpm reload

# MySQL
dbname=$app
dbuser=$app
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true

# Reload nginx service
sudo service nginx reload
